# Generated by Django 4.0.5 on 2022-08-13 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import guideapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('place', models.CharField(default='', max_length=50)),
                ('cost', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('address', models.CharField(default='', max_length=50)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RandomGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(choices=[('MOOD', 'Mood'), ('WEATHER', 'Weather'), ('WHO', 'Who'), ('REGION', 'Region'), ('ETC', 'Etc')], default='ETC', max_length=7)),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GuideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=guideapp.models.GuideImage.image_upload_path)),
                ('thumbnail', models.BooleanField(default=False)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='guideapp.guide')),
            ],
        ),
        migrations.AddField(
            model_name='guide',
            name='tag',
            field=models.ManyToManyField(related_name='guide', to='guideapp.tag'),
        ),
        migrations.AddField(
            model_name='guide',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide', to=settings.AUTH_USER_MODEL),
        ),
    ]
