# Generated by Django 4.0.4 on 2022-07-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guideapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='creator_id',
            field=models.CharField(max_length=10),
        ),
    ]
