# Generated by Django 4.0.5 on 2022-08-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guideapp', '0002_love'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='star',
            field=models.IntegerField(default=0),
        ),
    ]
