# Generated by Django 4.0.5 on 2022-07-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guideapp', '0004_alter_guide_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='date',
            field=models.DateField(),
        ),
    ]
