# Generated by Django 4.0.5 on 2022-08-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guideapp', '0005_alter_guide_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(choices=[('MOOD', 'Mood'), ('WEATHER', 'Weather'), ('WHO', 'Who'), ('REGION', 'Region'), ('ETC', 'Etc')], default='ETC', max_length=7)),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='guide',
            name='tag',
            field=models.ManyToManyField(to='guideapp.tag'),
        ),
    ]
