# Generated by Django 4.0.5 on 2022-08-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guideapp', '0006_tag_guide_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='tag',
            field=models.ManyToManyField(related_name='guide', to='guideapp.tag'),
        ),
    ]
