# Generated by Django 4.0.5 on 2022-08-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guideapp', '0007_alter_guide_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='guide',
            field=models.ManyToManyField(related_name='tag', to='guideapp.guide'),
        ),
    ]
