# Generated by Django 4.0.5 on 2022-08-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guideapp', '0008_remove_guide_tag_tag_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='guide',
        ),
        migrations.AddField(
            model_name='guide',
            name='tag',
            field=models.ManyToManyField(related_name='guide', to='guideapp.tag'),
        ),
    ]
