# Generated by Django 4.0.5 on 2022-08-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guideapp', '0009_remove_tag_guide_guide_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
