# Generated by Django 4.0.5 on 2022-08-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guideapp', '0010_randomguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
