# Generated by Django 4.0.5 on 2022-08-09 15:30

from django.db import migrations, models
import django.db.models.deletion
import guideapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('guideapp', '0011_alter_guide_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='thumbnail',
        ),
        migrations.CreateModel(
            name='GuideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=guideapp.models.GuideImage.image_upload_path)),
                ('thumbnail', models.BooleanField(default=False)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='guideapp.guide')),
            ],
        ),
    ]
