# Generated by Django 4.0.5 on 2022-08-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=15)),
                ('introduce', models.CharField(max_length=50)),
                ('프로필 이미지', models.ImageField(blank=True, max_length=400, upload_to='img/accounts/')),
                ('배경 이미지', models.ImageField(blank=True, max_length=400, upload_to='img/accounts/')),
            ],
        ),
    ]
