# Generated by Django 4.0.4 on 2022-08-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('email', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=15)),
                ('introduce', models.CharField(blank=True, max_length=50)),
                ('profile_photo', models.ImageField(blank=True, upload_to='img/accounts/')),
                ('header_photo', models.ImageField(blank=True, upload_to='img/accounts/')),
            ],
        ),
    ]
