# Generated by Django 3.2 on 2022-08-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KakaoUser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='header_photo',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='img/avatar/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
