# Generated by Django 4.0.5 on 2022-08-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('email', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=15)),
                ('introduce', models.CharField(blank=True, max_length=50)),
                ('profile_photo', models.TextField(blank=True)),
                ('header_photo', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
