# Generated by Django 3.2 on 2022-08-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_user_id_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='header_photo',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduce',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to=''),
        ),
    ]
