# Generated by Django 3.2 on 2022-08-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220810_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
