# Generated by Django 4.0.5 on 2022-08-14 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='header_photo',
        ),
    ]
