# Generated by Django 4.0.5 on 2022-08-14 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_user_header_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='KakaoUser',
        ),
    ]
