# Generated by Django 4.0.5 on 2022-08-13 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import memoryapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='memory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MemoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=memoryapp.models.MemoryImage.image_upload_path)),
                ('thumbnail', models.BooleanField(default=False)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='memoryapp.memory')),
            ],
        ),
    ]
