# Generated by Django 4.0.5 on 2022-07-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryapp', '0002_memoryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryimage',
            name='image',
            field=models.ImageField(default='media/dra.jpg', upload_to=''),
        ),
    ]
