# Generated by Django 4.0.5 on 2022-07-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryapp', '0003_alter_memoryimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoryimage',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='memory',
            name='thumbnail',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='memoryimage',
            name='image',
            field=models.ImageField(upload_to='img/memory/%Y%m%d'),
        ),
    ]
