# Generated by Django 4.0.5 on 2022-08-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryapp', '0005_alter_memoryimage_image_alter_memoryimage_memory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='memoryimage',
            name='thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
