# Generated by Django 4.0.4 on 2022-07-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_id', models.CharField(default='', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('place', models.CharField(default='', max_length=50)),
                ('cost', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('address', models.CharField(default='', max_length=50)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
