# Generated by Django 4.0.6 on 2022-07-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guideapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='buy',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
