# Generated by Django 4.0.4 on 2022-07-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guideapp', '0002_alter_guide_creator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='guideapp/img'),
        ),
    ]
